#!/usr/bin/env ruby

ignore 'web'

#
# Run thin server to give site a spin.
#
desc "start thin server"
task "serve" do
  sh "thin start -A file"
end

#
# Compile Handlebar.js templates.
#
desc "compile templates"
task 'compile' do
  sh "handlebars assets/templates/*.handlebars -f assets/javascripts/handlebars.templates.js"
end

#
# The publish task uses the detroit-github plugin
# from the Detroit project.
#
desc 'prepare'
task 'prepare' do
  github.prepare
end

desc 'publish'
task 'publish' do
  #mkdir_p 'website'
  #cp   'index.html', 'website/'
  #cp   'doc.json',   'website/'
  #cp_r 'assets',     'website/'
  github.publish 
end

#
# Helper method create Detroit::GitHub instace.
#
def github
  @github ||= (
    require 'detroit'
    require 'detroit-github'
 
    Detroit::GitHub.new(
      :folder  => 'website',
      :sitemap => {
        'index.html' => 'index.html',
        'doc.json'   => 'doc.json',
        'assets'     => 'assets'
      }
    )
  ) 
end

desc 'publish to heroku'
task 'heroku' do
  mkdir_p 'heroku'
  cp   'index.html', 'heroku/'
  cp   'doc.json',   'heroku/'
  cp_r 'assets',     'heroku/'
  cd 'heroku' do
    sh 'git push orgin master'
  end
end

